name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install backend dependencies
      working-directory: ./
      run: |
        python -m pip install --upgrade pip
        pip install -r ./backend/requirements.txt

    - name: Create backend .env file
      run: |
        echo "SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" > backend/backend/.env
        echo "DEBUG=False" >> backend/backend/.env
        echo "DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }}"  >> backend/backend/.env
        echo "CORS_ALLOW_ALL_ORIGINS=${{ secrets.CORS_ALLOW_ALL_ORIGINS }}"  >> backend/backend/.env
        echo "DB_PATH=" >> backend/backend/.env

    - name: Run backend tests
      run: python backend/manage.py test fuel_backend

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Create backend .env file
      run: |
        echo "VITE_BACKEND_API_URL=${{ secrets.VITE_BACKEND_API_URL }}" > frontend/.env
        
    - name: Run frontend tests
      working-directory: ./frontend
      run: npm test --ci